/* Load modules */
const express = require('express');
const path = require('path');
const handlebars = require('express-handlebars');

/* Import routes */
const reviews = require('./routes/reviews');

// Create our express server
const app = express();

// Set the port to the one specified in the env variable or 8080 for development
app.set('port', process.env.PORT || 8080);
// Serve static files from the 'dist' directory (generated by webpack)
app.use(express.static('dist'));
// Set our views path
app.set('views', path.join(__dirname, 'views'));
// Set our app to use the handlebars engine
app.engine('handlebars', handlebars());
app.set('view engine', 'handlebars');

/* Set routes */
app.get('/reviews', reviews.view);

// Start listening on the specified port
app.listen(app.get('port'), () => console.log(`Listening on port ${app.get('port')}!`));
